export enum GameListen {

    EVENT_RECEIVING_DESKSDATA = 'game_event_ReceivingDesksdata',

    PROTOCOL_LOGIN = 0,

    PROTOCOL_CHOOSE_TABLE = 1,

    PROTOCOL_SELECT_SEAT = 2,

    PROTOCOL_BUTTON_ACTION = 3,

    PROTOCOL_START = 4,

    PROTOCOL_BUTTON_LEAVESEAT = 5,

    PROTOCOL_BUTTON_LEAVEDESK = 6,

    PROTOCOL_BUTTON_HANGUP = 7,

    PROTOCOL_BUTTON_CANCELWAITBIG = 13,

    PROTOCOL_BUTTON_ADD_HAND_AMOUNT = 14

}
